---
title: C++Primer5 第5章 语句
date: 2021-12-24 20:39:40 +0800
tags: [笔记,C++Primer5,C++]
categories: [笔记,C++Primer5]
---

**说明：**本章主要讲述C++简单语句、条件语句、循环语句、跳转语句、以及用于异常处理的try语句。

1、多余的空语句并非总是无害的，所以不要少写或者多写;。

2、多个if-else语句中，会出现if多余else的问题（悬垂else问题），由于C++采取就近匹配准则，所以最好加上{}以控制执行路径，防止if-else的匹配与以及的编写意愿不同。

### switch语句

1、case关键字和它对应的值一起被称为case标签，case标签必须是整型常量表达式。

```c++
char ch = getval();
int val = 42;
switch(ch) {
    case 3.14:  // 错误 非整数
    case val:  // 错误 非常量
}
```

2、任何两个case标签的值不能相同，否则会错误。

3、如果某个case标签匹配成功，将从该标签开始往后顺序执行所有case分支。所以一般不要省略case分支最后的break语句，因为容易引发错觉（认为只执行匹配的case）。如果没有任何一个匹配的case，将执行default标签后面的语句。

4、标签不应该孤零零的出现，它后面必须跟上一条语句或者另外一个case标签。如果switch结构以一个空的default标签作为结束，default标签后面必须跟上一个空语句或一个空块。

5、如果需要为某个case分支定义并初始化一个变量，我们应该把变量定义在块内{}，从而保证后面的case标签都在变量的作用域之外，否则容易引发变量错误。

### 迭代语句

1、定义在`while`条件部分或者循环体内的变量每次迭代都经历从创建到销毁的过程。

2、`for`语句定义的对象只能在for循环体内可见。

3、和其他的声明一样，init-statement也可以定义多个对象，但是只能有一条声明语句，因此，所有变量的基础类型必须相同。

4、for语句头能省略掉init_statement、condition、expression中的一个或者全部。

5、`do while`语句应该在括号包围起来的条件后面用一个分号表示语句结束。因为对于do while来说先执行语句或者块，后判断条件，所以不允许在条件部分定义变量。

6、`break`语句负责终止离它最近的while、do while、for或switch语句，并从这些语句之后的第一条语句开始继续执行。

7、`continue`语句终止最近的循环中的当前迭代并立即开始下一次迭代。

8、不要在程序中使用goto语句！

### try语句块和异常处理

在C++中，异常处理包括：

* `throw`表达式，异常检测部分使用throw表达式来表示它遇到了无法处理的问题。我们说throw引发了异常。
* `try`语句块，异常处理部分使用try语句块处理异常。try语句块以关键字try开始，并以一个或多个`catch`子句处理。
* 一套异常类，用于在throw表达式和相关的catch子句之间传递异常的具体信息。

#### throw语句

程序的异常检测部分用throw表达式引发一个异常，throw表达式包含关键字throw和紧跟其后的一个表达式，其中表达式的类型就是抛出的异常类型。

```c++
if (items1.isbn() != items2.isbn())
    // 不一样就抛出异常 该异常是类型runtime_error的对象
    throw runtime_error("Data must refer to same ISBN");
```

#### try语句块

跟在try语句块之后的是一个或多个catch子句。catch子句包括三部分：关键字catch、括号内一个对象的声明（称为异常声明）、以及一个块。当选中了某个catch子句处理异常之后，就执行与之对应的块。catch一旦完成，程序跳转到try语句块最后一个catch子句之后的那条语句继续执行。

```c++
while (cin >> item1 >> item2){
	try{
		// 执行添加两个sales_item对象的代码
        // 如果添加失败 代码抛出一个runtime_error异常
    } catch (runtime_error err) {
		// 提醒用户两个对象输入必须一致 询问是否重新输出
        cout << err.what()
            << "\nTry again? Entry y or n" << endl;
        char c;
        cin >> c;
        if (!cin || c == 'n')
            break;  // 跳出while循环
    }
}
```

#### 函数在寻找处理代码的过程中退出

在复杂的系统中，程序在遇到抛出异常的代码前，其执行路径可能已经经过了多个try语句块。

寻找处理代码的过程与函数调用链刚好相反，沿着程序的执行路径逐层回退，知道找到适当类型的catch子句为止。

如果最终还是没有找到匹配的catch子句，程序赚到名为`terminate`的标准库函数，该函数的行为和系统有关，一般情况下，执行该函数将导致程序非正常退出。

如果一段程序没有try语句块并且发生了异常，系统会调用terminate函数并终止当前程序的执行。

#### 标准异常

C++定义了标准库异常类。**P176**

